spring.application.name=ASBproj-19-PaymentGatewayProfileSystem

spring.profiles.active=sms

email.senderName=Hasan
email.supportEmail=mohasan@gmail.com
email.notificationType=Email

sms.senderName=Hasan
sms.number=1234567890
sms.notificationType=SMS
