spring.application.name=ASBproj-27-NotificationServiceUsingProfile
spring.profiles.active=dev

car.name=Dezire
car.location=ameerpet to punjagutta
car.price=100

bike.name=Raider
bike.location=ameerpet to punjagutta
bike.price=70