spring.application.name=ASBproj-19-PaymentGatewayProfileSystem

spring.profiles.active=phonepay

phonepay.company=wipro
phonepay.limit=10000
phonepay.type=PhonePay

gpay.company=infosys
gpay.limit=15000
gpay.type=GooglePay

