spring.application.name=ASBproj-19-PaymentGatewayProfileSystem

spring.profiles.active=oracle

oracle.url=jdbc:oracle:thin:localhost:1521XE
oracle.username=hasan
oracle.dbName=Oracle

mysql.url=jdbc:mysql:thin:localhost:1521XE
mysql.username=root
mysql.dbName=MySQL