student:
  id: 101
  name: Ramesh
  course: Java
  fee: 45000
  institute: NareshIT
 
  subject:
  - Core JAva
  - Adv Java
  - Spring Boot

  marks:
   Java: 90
   Spring: 85
   SQL: 80